library(ridge)
atac.results <- readRDS('atac_results.rds')
pbm <- readRDS('pbm.rds')
svpdata <- data.frame(vals = atac.results[rownames(pbm),'lg2FC_svp'], pbm)
svpmodel <- linearRidge(vals ~ ., data = svpdata)
svppvals <- pvals(svpmodel)
saveRDS(svpmodel,'svp_ridge_model.rds')
saveRDS(svppvals,'svp_ridge_pvals.rds')
svndata <- data.frame(vals = atac.results[rownames(pbm),'lg2FC_svn'], pbm)
svnmodel <- linearRidge(vals ~ ., data = svndata)
svnpvals <- pvals(svnmodel)
saveRDS(svnmodel,'svn_ridge_model.rds')
saveRDS(svnpvals,'svn_ridge_pvals.rds')
